# Generated by Django 2.2.7 on 2019-11-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='Url2',
            field=models.URLField(default='https://shaparak.ir/'),
        ),
    ]
