# Generated by Django 2.2.7 on 2019-11-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blacklist_url2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='Url2',
        ),
    ]
