# Generated by Django 2.2.7 on 2019-12-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_blacklist_url2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='Name',
        ),
    ]
