# Generated by Django 2.2.7 on 2019-12-16 19:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_blacklist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('url_tel', models.URLField(default='https://t.me/mahana_app')),
                ('url_ins', models.URLField(default='www.instagram.com/ego_official2018')),
                ('url_site', models.URLField(default='https://www.danapco.com/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+989010979406', max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
                'ordering': ('-created',),
            },
        ),
    ]
